### ISSUE TITLE
Unexpected end of input?

### ISSUE THREAD

**Issue by kenichi-shibata** [rejas/gulp-json-editor#12]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Transform._transform (/Users/00831103/Workspace/project-2/node_modules/gulp-json-editor/index.js:65:45)
    at Transform._read (/Users/00831103/Workspace/project-2/node_modules/gulp-json-editor/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/00831103/Workspace/project-2/node_modules/gulp-json-editor/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/00831103/Workspace/project-2/node_modules/gulp-json-editor/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/00831103/Workspace/project-2/node_modules/gulp-json-editor/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/00831103/Workspace/project-2/node_modules/gulp-json-editor/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/00831103/Workspace/project-2/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/00831103/Workspace/project-2/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/00831103/Workspace/project-2/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

code is 

```
var gulp = require('gulp');
var jeditor   = require('gulp-json-editor');
gulp.task('addjson','adds basic placeholder json',function(){
  return gulp.src('./aggregate.json')
  .pipe(jeditor(function(json) {
    json = "1.2.3";
    return json; // must return JSON object.
  }))
  .pipe(gulp.dest('.'));
});
```

**Comment by tinyfly** [comment]
That is node telling you and error was thrown but there was nothing to catch it so the node process died.  Try adding an error handler after the jeditor pipe.

```javascript
.on('error', function(err) {
  console.error(err.message);
})
```

Of course a real error handler function would be more robust but this should give you an idea of what the actual error was.

**Comment by rejas** [comment]
hi  @kenichi-shibata is this still an issue for you? if yes, could you test again with the latest version and post your recent configs/data?

**Comment by rejas** [comment]
Closing due to inactivity.
