### ISSUE TITLE
"Buffer.from(json)" happens crash

### ISSUE THREAD

**Issue by TyssenLove** [rejas/gulp-json-editor#21]
![image](https://user-images.githubusercontent.com/13833916/42358285-6feaed98-810e-11e8-91b6-200e902e0efd.png) 
![Uploading WX20180706-112514@2x.png…]()

on node version 10.4.1 and 6.0.0 , both of them occur exception. Is it a bug?

`TypeError: this is not a typed array.
    at Function.from (native)
    at DestroyableTransform._transform (/Users/a/work/project/AutoUI_Client/node_modules/_gulp-json-editor@2.4.1@gulp-json-editor/index.js:71:30)
    at DestroyableTransform.Transform._read (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@2.3.6@readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@2.3.6@readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@2.3.6@readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@2.3.6@readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@2.3.6@readable-stream/lib/_stream_writable.js:334:11)
    at write (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/a/work/project/AutoUI_Client/node_modules/_through2@0.6.5@through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/a/work/project/AutoUI_Client/node_modules/_readable-stream@1.0.34@readable-stream/lib/_stream_transform.js:172:12)`

**Comment by rejas** [comment]
Hi @TyssenLove could you also post your config and code how you call the plugin? Thx

**Comment by rejas** [comment]
Closing due to inactivity
